// fixed row length at the queue
const ROW_LENGTH = 40;

const OPEN_FILE_ONCE_MUTEX_IDX = 0;
const OPEN_FILE_ONCE_SYNCED_FLAG_IDX = 1;
const QUEUE_FILE_DESCRIPTOR_IDX = 2;
const QUEUE_MUTEX_IDX = 3;
const QUEUE_BYTE_SIZE_IDX = 4;
const SHARED_MEMORY_LEN =  QUEUE_BYTE_SIZE_IDX + 1;

module.exports = {
    ROW_LENGTH,
    OPEN_FILE_ONCE_MUTEX_IDX,
    OPEN_FILE_ONCE_SYNCED_FLAG_IDX,
    QUEUE_FILE_DESCRIPTOR_IDX,
    QUEUE_MUTEX_IDX,
    QUEUE_BYTE_SIZE_IDX,
    SHARED_MEMORY_LEN
};
